### ISSUE TITLE
#333 or #000 — make up (y)our mind!

### ISSUE THREAD

**Issue by galenwp** [urbit/base-css#25]
A link inside of a header is `#000` (set on `a`), and a header is `#333` (set on `h*`).

wth.

**Comment by galenwp** [comment]
@jyng @c-johnson do we have strong opinions about black vs #333? I say go all black.

**Comment by galenwp** [comment]
Oh also @gavinpatkinson

**Comment by gavinpatkinson** [comment]
I say all #000
