### ISSUE TITLE
Curious about the type scale (typography.scss)

### ISSUE THREAD

**Issue by jyng** [urbit/base-css#4]
Hello,
I'm interested in learning about the decisions made on the type scale. Particularly:
- Why is the base font-size 6px? 
My strong opinion is that sticking with the base browser font size (16px) leads to a more manageable and efficient type system on the web.
- What is the scale ratio being applied here?
It looks like a Major Third (1.25) but not quite?
![typography 1](https://user-images.githubusercontent.com/9557907/30012068-aa6a79f6-90f1-11e7-87a7-110188c9d14e.jpg)

A bit about me:
I'm a designer that I came across Urbit through a friend. I'm a fan of Urbit and find that it's something that needs to exist for a better internet.

**Comment by galenwp** [comment]
Hello!  Glad to hear there are designers interested in Urbit!

Just FYI: this project (`base-css`) is still pretty much just Chris and I collaborating.  The idea is to use this as a new base stylesheet for all of Urbit.  We're getting close to something that can be shown off to the public, but we're not quite there yet.  

Anyway, to your points:

- We wanted to pick a base font size that could act as a baseline grid for *everything*.  So, we do land on 18px over 16px.  I suppose you could switch to 4px instead.  Is 4px a convention I'm not aware of?  I do tend to favor values divisible by three, but could probably be convinced 4 is better.
- Yes, it's close to a major third — but making the steps within steps that are divisible by 6 so as to not break the baseline grid.

Happy to hear further criticism here.

**Comment by jyng** [comment]
Hey Galen, 
Sorry I was bit occupied with traveling. 
Yes! Definitely excited about Urbit and would love to help out on design. Btw, I came by way through Edouard 😁 
On baseline grid:
I weighed a lot of the pros and cons of 6px vs 4px and found some minor differences. 
- I thought that 4px was superior in viewport sizing, but I think most viewports are divisible by 6px and 4px. So, both options are well suited for responsive design.
- 4px is a multiple of base font size (16px) and thus you can work with the browser as opposed to working against it.
- 4 is a strong number for Urbit. Address spaces are all multiples of 4. Urbit's virtual city endpoint is 4 billion. I know there has been talk about Urbit having as little brand as possible, but I still find meaningful numbers to be a core principle in building a system.

As always, would love to hear your criticisms as well. I love to be wrong.

**Comment by galenwp** [comment]
I think your last point is the most convincing, but for a slightly different reason than you state.  Urbit tends to use base two numbers (2<sup>32</sup> = ~4B.  

Since 2<sup>2</sup> = 4 it does feel right.
