### ISSUE TITLE
npm serve not working on my instance

### ISSUE THREAD

**Issue by jyng** [urbit/base-css#5]
Hello again! Just tried to run `npm serve` but I'm running into an error (see screenshot). In the past, I've started npm stuff with `npm start` but that doesn't seem to work either?
<img width="809" alt="screen shot 2017-09-04 at 3 59 53 pm" src="https://user-images.githubusercontent.com/9557907/30039762-56460388-918a-11e7-8f4d-acf9796ce28b.png">

**Comment by galenwp** [comment]
I think what you're looking for is `npm run serve`.  Will update the readme to reflect that.

Looks to me like the build is failing here.  This is pretty raw stuff!  If I roll back to my last commit it seems to work.  Try:

```
$ git checkout 22f2a7421180cd7069672e0bbe336ecc240ff8a2
$ npm run serve
```

Then open a browser at `http://localhost:8080/index.html`.

@c-johnson could you push your latest when you get a chance?  

I fail with:

```
{
  "status": 1,
  "file": "/Users/galen/src/base-css/sass/base.scss",
  "line": 5,
  "column": 1,
  "message": "File to import not found or unreadable: layout.\nParent style sheet: /Users/galen/src/base-css/sass/base.scss",
  "formatted": "Error: File to import not found or unreadable: layout.\n       Parent style sheet: /Users/galen/src/base-css/sass/base.scss\n        on line 5 of sass/base.scss\n>> @import \"layout\";\n   ^\n"
}
```

Which looks like a file I added, but perhaps has been deprecated.  Not sure what the current file structure looks like.

**Comment by jyng** [comment]
Awesome, I rolled back and that worked 👍 
I was going to ask if there was some working style guide, but looks like it's all here 😃

**Comment by galenwp** [comment]
It's a start! There's still more to add.
